//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Accountancy.Web.App.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditOutgoingCreditNoteDraft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditOutgoingCreditNoteDraft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Accountancy.Web.App.Resources.Pages.EditOutgoingCreditNoteDraft", typeof(EditOutgoingCreditNoteDraft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error issuing credit note from draft.
        /// </summary>
        public static string CreditNoteIssuedFromDraftErrorMessage {
            get {
                return ResourceManager.GetString("CreditNoteIssuedFromDraftErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit note issued correctly from draft!.
        /// </summary>
        public static string CreditNoteIssuedFromDraftSuccessMessage {
            get {
                return ResourceManager.GetString("CreditNoteIssuedFromDraftSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The draft you&apos;re searching for does not exist.
        /// </summary>
        public static string DraftNotFoundMessageText {
            get {
                return ResourceManager.GetString("DraftNotFoundMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating this draft. Please, try again later.
        /// </summary>
        public static string DraftUpdateErrorMessage {
            get {
                return ResourceManager.GetString("DraftUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft update successfully!.
        /// </summary>
        public static string DraftUpdateSuccessMessage {
            get {
                return ResourceManager.GetString("DraftUpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit outgoing credit note draft.
        /// </summary>
        public static string PageHeaderText {
            get {
                return ResourceManager.GetString("PageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merp - Accountancy - Edit outgoing credit note draft.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, search another draft.
        /// </summary>
        public static string SearchAnotherDraftMessageText {
            get {
                return ResourceManager.GetString("SearchAnotherDraftMessageText", resourceCulture);
            }
        }
    }
}
