//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Accountancy.Web.App.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Accountancy.Web.App.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a job order.
        /// </summary>
        public static string CreateJobOrderMenuItemLabel {
            get {
                return ResourceManager.GetString("CreateJobOrderMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string InvoicesMenuLabel {
            get {
                return ResourceManager.GetString("InvoicesMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue a credit note.
        /// </summary>
        public static string IssueCreditNoteMenuItemLabel {
            get {
                return ResourceManager.GetString("IssueCreditNoteMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue an invoice.
        /// </summary>
        public static string IssueInvoiceMenuItemLabel {
            get {
                return ResourceManager.GetString("IssueInvoiceMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job orders.
        /// </summary>
        public static string JobOrdersMenuLabel {
            get {
                return ResourceManager.GetString("JobOrdersMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link an incoming invoice to a job order.
        /// </summary>
        public static string LinkIncomingInvoiceToJobOrderMenuItemLabel {
            get {
                return ResourceManager.GetString("LinkIncomingInvoiceToJobOrderMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link an outgoing invoice to a job order.
        /// </summary>
        public static string LinkOutgoingInvoiceToJobOrderMenuItemLabel {
            get {
                return ResourceManager.GetString("LinkOutgoingInvoiceToJobOrderMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountancy.
        /// </summary>
        public static string PageHeaderText {
            get {
                return ResourceManager.GetString("PageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merp - Accountancy.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an incoming credit note.
        /// </summary>
        public static string RegisterIncomingCreditNoteMenuItemLabel {
            get {
                return ResourceManager.GetString("RegisterIncomingCreditNoteMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an incoming invoice.
        /// </summary>
        public static string RegisterIncomingInvoiceMenuItemLabel {
            get {
                return ResourceManager.GetString("RegisterIncomingInvoiceMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an outgoing credit note.
        /// </summary>
        public static string RegisterOutgoingCreditNoteMenuItemLabel {
            get {
                return ResourceManager.GetString("RegisterOutgoingCreditNoteMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an outgoing invoice.
        /// </summary>
        public static string RegisterOutgoingInvoiceMenuItemLabel {
            get {
                return ResourceManager.GetString("RegisterOutgoingInvoiceMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search invoices.
        /// </summary>
        public static string SearchInvoicesMenuItemLabel {
            get {
                return ResourceManager.GetString("SearchInvoicesMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search job orders.
        /// </summary>
        public static string SearchJobOrdersMenuItemLabel {
            get {
                return ResourceManager.GetString("SearchJobOrdersMenuItemLabel", resourceCulture);
            }
        }
    }
}
