//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Accountancy.Web.App.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchInvoices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchInvoices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Accountancy.Web.App.Resources.Pages.SearchInvoices", typeof(SearchInvoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerColumn {
            get {
                return ResourceManager.GetString("CustomerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerSearchLabel {
            get {
                return ResourceManager.GetString("CustomerSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        public static string DateOfIssueColumn {
            get {
                return ResourceManager.GetString("DateOfIssueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string DocumentTypeColumn {
            get {
                return ResourceManager.GetString("DocumentTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string DueDateColumn {
            get {
                return ResourceManager.GetString("DueDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromDateSearchLabel {
            get {
                return ResourceManager.GetString("FromDateSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string InvoiceDetailsButtonText {
            get {
                return ResourceManager.GetString("InvoiceDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string InvoiceKindAny {
            get {
                return ResourceManager.GetString("InvoiceKindAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncomingCreditNotes.
        /// </summary>
        public static string InvoiceKindIncomingCreditNotes {
            get {
                return ResourceManager.GetString("InvoiceKindIncomingCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncomingInvoices.
        /// </summary>
        public static string InvoiceKindIncomingInvoices {
            get {
                return ResourceManager.GetString("InvoiceKindIncomingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutgoingCreditNotes.
        /// </summary>
        public static string InvoiceKindOutgoingCreditNotes {
            get {
                return ResourceManager.GetString("InvoiceKindOutgoingCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutgoingInvoices.
        /// </summary>
        public static string InvoiceKindOutgoingInvoices {
            get {
                return ResourceManager.GetString("InvoiceKindOutgoingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice kind.
        /// </summary>
        public static string InvoiceKindSearchLabel {
            get {
                return ResourceManager.GetString("InvoiceKindSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice nr..
        /// </summary>
        public static string InvoiceNumberColumn {
            get {
                return ResourceManager.GetString("InvoiceNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string InvoiceStateAny {
            get {
                return ResourceManager.GetString("InvoiceStateAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        public static string InvoiceStateOutstanding {
            get {
                return ResourceManager.GetString("InvoiceStateOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string InvoiceStateOverdue {
            get {
                return ResourceManager.GetString("InvoiceStateOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string InvoiceStatePaid {
            get {
                return ResourceManager.GetString("InvoiceStatePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice status.
        /// </summary>
        public static string InvoiceStateSearchLabel {
            get {
                return ResourceManager.GetString("InvoiceStateSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue credit note.
        /// </summary>
        public static string IssueCreditNoteButtonText {
            get {
                return ResourceManager.GetString("IssueCreditNoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue invoice.
        /// </summary>
        public static string IssueInvoiceButtonText {
            get {
                return ResourceManager.GetString("IssueInvoiceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoices found. Please, try to specify other search terms..
        /// </summary>
        public static string NoInvoicesFoundText {
            get {
                return ResourceManager.GetString("NoInvoicesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search invoices.
        /// </summary>
        public static string PageHeaderText {
            get {
                return ResourceManager.GetString("PageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merp - Accountancy - Search Invoices.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items of {1}.
        /// </summary>
        public static string PaginationItemsNumberText {
            get {
                return ResourceManager.GetString("PaginationItemsNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceColumn {
            get {
                return ResourceManager.GetString("PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string PurchasesButtonText {
            get {
                return ResourceManager.GetString("PurchasesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register incoming credit note.
        /// </summary>
        public static string RegisterIncomingCreditNoteButtonText {
            get {
                return ResourceManager.GetString("RegisterIncomingCreditNoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register incoming invoice.
        /// </summary>
        public static string RegisterIncomingInvoiceButtonText {
            get {
                return ResourceManager.GetString("RegisterIncomingInvoiceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register outgoing credit note.
        /// </summary>
        public static string RegisterOutgoingCreditNoteButtonText {
            get {
                return ResourceManager.GetString("RegisterOutgoingCreditNoteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register outgoing invoice.
        /// </summary>
        public static string RegisterOutgoingInvoiceButtonText {
            get {
                return ResourceManager.GetString("RegisterOutgoingInvoiceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string SalesButtonText {
            get {
                return ResourceManager.GetString("SalesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierColumn {
            get {
                return ResourceManager.GetString("SupplierColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierSearchLabel {
            get {
                return ResourceManager.GetString("SupplierSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToDateSearchLabel {
            get {
                return ResourceManager.GetString("ToDateSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View drafts.
        /// </summary>
        public static string ViewDraftsButtonText {
            get {
                return ResourceManager.GetString("ViewDraftsButtonText", resourceCulture);
            }
        }
    }
}
