//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Accountancy.Web.App.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueInvoiceForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueInvoiceForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Accountancy.Web.App.Resources.Components.IssueInvoiceForm", typeof(IssueInvoiceForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyTextLabel {
            get {
                return ResourceManager.GetString("CurrencyTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerAutocompleteLabel {
            get {
                return ResourceManager.GetString("CustomerAutocompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateDatepickerLabel {
            get {
                return ResourceManager.GetString("DateDatepickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionTextLabel {
            get {
                return ResourceManager.GetString("DescriptionTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string IssueButtonText {
            get {
                return ResourceManager.GetString("IssueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment terms.
        /// </summary>
        public static string PaymentTermsTextLabel {
            get {
                return ResourceManager.GetString("PaymentTermsTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order number.
        /// </summary>
        public static string PurchaseOrderNumberTextLabel {
            get {
                return ResourceManager.GetString("PurchaseOrderNumberTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as draft.
        /// </summary>
        public static string SaveAsDraftButtonText {
            get {
                return ResourceManager.GetString("SaveAsDraftButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable amount.
        /// </summary>
        public static string TaxableAmountText {
            get {
                return ResourceManager.GetString("TaxableAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string TaxesText {
            get {
                return ResourceManager.GetString("TaxesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot. price.
        /// </summary>
        public static string TotalPriceText {
            get {
                return ResourceManager.GetString("TotalPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string TotalsSectionTitle {
            get {
                return ResourceManager.GetString("TotalsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay.
        /// </summary>
        public static string TotalToPayText {
            get {
                return ResourceManager.GetString("TotalToPayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT included.
        /// </summary>
        public static string VatIncludedCheckboxLabel {
            get {
                return ResourceManager.GetString("VatIncludedCheckboxLabel", resourceCulture);
            }
        }
    }
}
