//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Registry.Web.Api.Private.Resources.Party {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Registry.Web.Api.Private.Resources.Party.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete the party.
        /// </summary>
        internal static string ConfirmPartyUnlistMessage {
            get {
                return ResourceManager.GetString("ConfirmPartyUnlistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ConfirmPartyUnlistQuestion {
            get {
                return ResourceManager.GetString("ConfirmPartyUnlistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete party.
        /// </summary>
        internal static string DeleteParty {
            get {
                return ResourceManager.GetString("DeleteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items of.
        /// </summary>
        internal static string ItemsOf {
            get {
                return ResourceManager.GetString("ItemsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string PartyAddCompany {
            get {
                return ResourceManager.GetString("PartyAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string PartyAddPerson {
            get {
                return ResourceManager.GetString("PartyAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical (ascending).
        /// </summary>
        internal static string PartyFilterOrderingNameAsc {
            get {
                return ResourceManager.GetString("PartyFilterOrderingNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical (descending).
        /// </summary>
        internal static string PartyFilterOrderingNameDesc {
            get {
                return ResourceManager.GetString("PartyFilterOrderingNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string PartyFilterTypeAny {
            get {
                return ResourceManager.GetString("PartyFilterTypeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string PartyFilterTypeCompany {
            get {
                return ResourceManager.GetString("PartyFilterTypeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string PartyFilterTypePerson {
            get {
                return ResourceManager.GetString("PartyFilterTypePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PartyListName {
            get {
                return ResourceManager.GetString("PartyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone #.
        /// </summary>
        internal static string PartyListPhoneNumber {
            get {
                return ResourceManager.GetString("PartyListPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PartySearchFilterName {
            get {
                return ResourceManager.GetString("PartySearchFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string PartySearchFilterSort {
            get {
                return ResourceManager.GetString("PartySearchFilterSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PartySearchFilterType {
            get {
                return ResourceManager.GetString("PartySearchFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string PartySearchPageTitle {
            get {
                return ResourceManager.GetString("PartySearchPageTitle", resourceCulture);
            }
        }
    }
}
