//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Registry.Web.Resources.Party {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Registry.Web.Resources.Party.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are going to delete the party.
        /// </summary>
        internal static string ConfirmPartyUnlistMessage {
            get {
                return ResourceManager.GetString("ConfirmPartyUnlistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure?.
        /// </summary>
        internal static string ConfirmPartyUnlistQuestion {
            get {
                return ResourceManager.GetString("ConfirmPartyUnlistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete party.
        /// </summary>
        internal static string DeleteParty {
            get {
                return ResourceManager.GetString("DeleteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a items of.
        /// </summary>
        internal static string ItemsOf {
            get {
                return ResourceManager.GetString("ItemsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company.
        /// </summary>
        internal static string PartyAddCompany {
            get {
                return ResourceManager.GetString("PartyAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Person.
        /// </summary>
        internal static string PartyAddPerson {
            get {
                return ResourceManager.GetString("PartyAddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alphabetical (ascending).
        /// </summary>
        internal static string PartyFilterOrderingNameAsc {
            get {
                return ResourceManager.GetString("PartyFilterOrderingNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alphabetical (descending).
        /// </summary>
        internal static string PartyFilterOrderingNameDesc {
            get {
                return ResourceManager.GetString("PartyFilterOrderingNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Any.
        /// </summary>
        internal static string PartyFilterTypeAny {
            get {
                return ResourceManager.GetString("PartyFilterTypeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company.
        /// </summary>
        internal static string PartyFilterTypeCompany {
            get {
                return ResourceManager.GetString("PartyFilterTypeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Person.
        /// </summary>
        internal static string PartyFilterTypePerson {
            get {
                return ResourceManager.GetString("PartyFilterTypePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string PartyListName {
            get {
                return ResourceManager.GetString("PartyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone #.
        /// </summary>
        internal static string PartyListPhoneNumber {
            get {
                return ResourceManager.GetString("PartyListPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string PartySearchFilterName {
            get {
                return ResourceManager.GetString("PartySearchFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sort.
        /// </summary>
        internal static string PartySearchFilterSort {
            get {
                return ResourceManager.GetString("PartySearchFilterSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string PartySearchFilterType {
            get {
                return ResourceManager.GetString("PartySearchFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        internal static string PartySearchPageTitle {
            get {
                return ResourceManager.GetString("PartySearchPageTitle", resourceCulture);
            }
        }
    }
}
