//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merp.Accountancy.Web.Resources.Invoice {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutgoingInvoiceDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutgoingInvoiceDetails() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merp.Accountancy.Web.Resources.Invoice.OutgoingInvoiceDetails", typeof(OutgoingInvoiceDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taxable amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date of issue.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invoice lines.
        /// </summary>
        internal static string InvoiceLines {
            get {
                return ResourceManager.GetString("InvoiceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invoice totals.
        /// </summary>
        internal static string InvoiceTotals {
            get {
                return ResourceManager.GetString("InvoiceTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Code.
        /// </summary>
        internal static string LineItemCode {
            get {
                return ResourceManager.GetString("LineItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Qty.
        /// </summary>
        internal static string LineItemQuantity {
            get {
                return ResourceManager.GetString("LineItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tot. price.
        /// </summary>
        internal static string LineItemTotalPrice {
            get {
                return ResourceManager.GetString("LineItemTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unit price.
        /// </summary>
        internal static string LineItemUnitPrice {
            get {
                return ResourceManager.GetString("LineItemUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAT.
        /// </summary>
        internal static string LineItemVat {
            get {
                return ResourceManager.GetString("LineItemVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Payment date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Payment terms.
        /// </summary>
        internal static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PO #.
        /// </summary>
        internal static string PurchaseOrderNumber {
            get {
                return ResourceManager.GetString("PurchaseOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAT incl..
        /// </summary>
        internal static string VatIncluded {
            get {
                return ResourceManager.GetString("VatIncluded", resourceCulture);
            }
        }
    }
}
