// <auto-generated />
namespace Merp.Web.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Accountancy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accountancy));
        
        string IMigrationMetadata.Id
        {
            get { return "201408010838007_Accountancy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
