// <auto-generated />
namespace Merp.Web.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class JobOrderCurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobOrderCurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201502232212064_JobOrder-Currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
