// <auto-generated />
namespace Merp.Web.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InvoicePaymentAndExpirationDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoicePaymentAndExpirationDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201610252057149_Invoice-PaymentAndExpirationDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
