// <auto-generated />
namespace Merp.Accountancy.QueryStack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AccountancyBaseSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountancyBaseSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201708281522242_Accountancy-BaseSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
